
# todo: ARCHIVE THIS FILE, IT IS NOT USED ANYMORE

# ---- STUDENTS ----
ACCEPTABLE_STUDENT_GENDER = ["Male", "Female", "Unknown"]
ACCEPTABLE_ENGLISH_LEARNER = ["Yes", "No"]
ACCEPTABLE_LIVING_ARRANGEMENT = ["Boarding House", "Cooperative House", "Crisis Shelter", "Disaster Shelter", "Family Residence", "Foster Home", "Group Home/Halfway House",
                                 "Institution", "No Home", "Other", "Other Dormitory", "Prison or Juvenile Detention Center", "Residential School/Dormitory",
                                 "Rooming House", "Transient Shelter", "Unknown"
                                 ]
ACCEPTABLE_BLOOD_TYPE = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]
ACCEPTABLE_STUDENT_RACE = ["American Indian or Alaska Native", "Asian", "Asian Indian", "Black or African American",
                           "Blank (Not set)", "Chinese", "Filipino", "Guamanian or Chamoorro",
                           "Japanese", "Korean", "More than One Race", "Native Hawaiian", "Other Asian",
                           "Other Pacific Islander", "Samoan", "Some Other Race", "Unknown", "Vietnamese",
                           "White"
                           ]
ACCEPTABLE_STUDENT_ETHNICITY = ["Amer Ind & Pacific Islander", "Amer Ind or Alaskan Native", "Arab", "Asian", "Asian & Am Ind/Alaskan Nat",
                                "Asian & Blank/African Amer", "Asian & Hispanic", "Asian & Pacific Islander", "Asian & White",
                                "Black & Am Ind/Alaska Nat", "Black & Pacific Islander", "Black/African Amer & Hispanic", "Black/African Amer & White",
                                "Black/AFrican American", "Declined to State", "Hawaiian or Other Pacific Islander", "Hispanic", "Hispanic & Am Ind/Ak Nat",
                                "Hispanic & Pacific Islander", "Hispanic & White", "Hispanic Origin", "Indian", "NA", "Native Indian", "Not of Hispanic Origin",
                                "Other", "Unknown", "White", "White & Am Ind/Alaskan Nat", "White & Pacific Islander"
                                ]
ACCEPTABLE_MEMBERSHIP_TYPE = ["Home", "Concurrent", "Summer"]
ACCEPTABLE_GRADE_LEVEL = [str(i) for i in range(1, 13)] + ["Early Dev", "Head Start", "Infant", "KG1", "KG 2", "Other", "Postgraduate/Adult", "Preschool", "Spec. Ed.", "Toddler", "Ungraded", "Unknown"]
ACCEPTABLE_BOOLEAN = ["Yes", "No"]

# ---- CONTACTS ----
ACCEPTABLE_CONTACTS_GENDER = ["Male", "Female", "Unknown"]
ACCEPTABLE_BOOLEAN = ["Yes", "No"]

# ---- FACULTY ----
ACCEPTABLE_FACULTY_GENDER = ["Male", "Female", "Unknown"]
ACCEPTABLE_BOOLEAN = ["Yes", "No"]

# ---- IMMUNIZATIONS ----
ACCEPTABLE_VACCINES = [
    "Anthrax (Biothrax)",
    "BCG",
    "COVID-19 (AstraZeneca)",
    "COVID-19 (Johnson and Johnson 0.5 mL)",
    "COVID-19 (Moderna 0.25mL)",
    "COVID-19 (Moderna 0.5 mL)",
    "COVID-19 (Moderna Bivalent 0.5 mL)",
    "COVID-19 (Pfizer 0.2 mL)",
    "COVID-19 (Pfizer 0.3 mL)",
    "COVID-19 (Pfizer Bivalent 0.3 mL)",
    "COVID-19 (Unknown)",
    "DT (Unknown)",
    "DTaP (Daptacel)",
    "DTaP (Infanrix)",
    "DTaP (Tripedia)",
    "DTaP (Unknown)",
    "DTaP-IPV (Kinrix)",
    "DTaP-IPV/Hib (Pentacel)",
    "DTaP/HepB/IPV/HIB (Hexaxim)",
    "DTaP/Hib (TriHIBit)",
    "DTaP/IPV (Quadracel)",
    "Dtap/IPV (unknown)",
    "DTaP/IPV/HepB (Pediarix)",
    "DTaP/IPV/Hib/HepB (Hexavalent)",
    "DTaP/IPV/Hib/HepB (Vaxelis)",
    "DTP (Unknown)",
    "DTP/Hib (Tetramune)",
    "DTP/Hib/HepB (Pentavalent)",
    "HepA (Havrix)",
    "HepA (Unknown)",
    "HepA (Vaqta)",
    "HepA/HepB (Ambirix)",
    "HepA/HepB (TwinRix)",
    "HepB (Unknown)",
    "HepB/Hib (Comvax)",
    "HepB:2 dose (Recombivax HB 1.0mL)",
    "HepB:2 dose (Unknown)",
    "HepB:3 dose (Recombivax HB 0.5mL)",
    "Hib (ActHIB)",
    "Hib (HibTITER)",
    "Hib (PedvaxHIB)",
    "Hib (Unknown)",
    "Hib (Hiberix only)",
    "Hib/Meningococcal (menhibrix)",
    "HPV (HPV2) (Cervarix)",
    "HPV (HPV4) (Gardasil)",
    "HPV (HPV9) (Gardasil 9)",
    "HPV (HPV9) (Unknown)",
    "HPV (Unknown)",
    "Influenza (Afluria Quadrivalent 0.5 mL)",
    "Influenza (FLU QUAD P)",
    "Influenza (FLU TRI P)",
    "Influenza (FLU6-35 P)",
    "Influenza (LAIV) (FluMist Intranasal)",
    "Influenza (TIV) (Afluria)",
    "Influenza (TIV) (Fluarix)",
    "Influenza (TIV) (FluLaval)",
    "Influenza (TIV) (Fluzone 0.25mL)",
    "Influenza (TIV) (Fluzone 0.5mL)",
    "Influenza (TIV) Fluvirin)",
    "Influenza (Unknown)",
    "Influenza - H1N1 (Unknown)",
    "Japanese Encephalitis (JE-Vax)",
    "Measles (Attenuvax)",
    "Measles (Unknown)",
    "Meningococcal (MCV4) (Menactra)",
    "Meningococcal (MCV4) (Unknown)",
    "Meningococcal (MenB) (Bexsero)",
    "Meningococcal (MenB) (Trumenba)",
    "Meningococcal (MenB) (Unknown)",
    "Meningococcal (Menveo)",
    "Meningococcal (MPSV4) (Menomune)",
    "Meningococcal A (Unknown)",
    "Meningococcal ACYW (MenQuadfi)",
    "Meningococcal C (Unknown)",
    "MMR (M-M-R II)",
    "MMR (Unknown)",
    "MMRV (ProQuad)",
    "Mumps (Mumpsvax)",
    "Mumps (Unknown)",
    "Pneumococcal (PCV13) (Prevnar)",
    "Pneumococcal (PCV7) (Prevnar)",
    "Pneumococcal (PPSV23) (Pneumovax 23)",
    "Pneumococcal (Unknown)",
    "Pneumococcal (Vaxneuvance)",
    "Polio (IPV) (IPOL)",
    "Polio (OPV)",
    "Polio (Unknown)",
    "Polio (Bivalent)",
    "Polio (Trivalent)",
    "Rabies (BioRab)",
    "Rabies (Imovax Rabies)",
    "Rabies (RabAvert)",
    "Rabies (Unknown)",
    "Rotarix",
    "Rotavirus (RotaTeq)",
    "Rotavirus (Unknown)",
    "RSV (Synagis) (Palivizumab)",
    "Rubella (Meruvax II)",
    "Rubella (Unknown)",
    "Td (Decavac)",
    "Td (Unknown)",
    "Tdap (Adacel)",
    "Tdap (Boostrix)",
    "Tdap (Unknown)",
    "Tetanus Toxoid (Unknown)",
    "Tetanus Toxoid Adsorbed (MA)",
    "Tetanus Toxoid Adsorbed (sanofi)",
    "TT (Generic)",
    "Typhoid (TYPHIM Vi)",
    "Typhoid (Vivotif) (Berna)",
    "Vaccina (Smallpox) (ACAM2000)",
    "Vaccina (Smallpox) (Dryvax)",
    "Varicella (Unknown)",
    "Varicella (Varivax)",
    "Yellow Fever (YF-Vax)",
    "Yellow Fever (Stamanil)",
    "Zoster Vaccine Live (Zostavax)"
]

